name: Deploy Azure Function App & Logic App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Optional: Restart the Function App to ensure it's not in read-only mode
      - name: Restart Function App
        run: |
          az functionapp restart \
            --name healthcheckfunc-jiga \
            --resource-group rg-order-logic-northeurope

      - name: Deploy Logic App (Alerting)
        run: |
          az deployment group create \
            --name logicapp-alerting-${{ github.run_number }} \
            --resource-group rg-order-logic-northeurope \
            --template-file ./infra/logicapp.bicep \
            --parameters \
              healthCheckUrl='${{ secrets.HEALTHCHECK_URL }}' \
              appInsightsIKey='${{ secrets.APPINSIGHTS_INSTRUMENTATION_KEY }}' \
              appInsightsKey='${{ secrets.APPINSIGHTS_API_KEY }}'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.313'


      - name: Restore dependencies
        run: dotnet restore ./Azure-Healthcheck

      - name: Build project
        run: dotnet build ./Azure-Healthcheck --configuration Release

      - name: Publish Function App
        run: dotnet publish ./Azure-Healthcheck --configuration Release --output ./publish

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: healthcheckfunc-jiga
          package: ./publish
