name: Deploy Azure Function App & Infra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep template
        run: |
          az deployment group create \
            --name logicapp-deploy-${{ github.run_number }} \
            --resource-group rg-order-logic-northeurope \
            --template-file ./infra/check.bicep

          az deployment group create \
            --name logicapp-alerting-${{ github.run_number }} \
            --resource-group rg-order-logic-northeurope \
            --template-file ./infra/logicapp.bicep

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Azure-Healthcheck

      - name: Build project
        run: dotnet build ./Azure-Healthcheck --configuration Release

      - name: Publish Function App
        run: dotnet publish ./Azure-Healthcheck --configuration Release --output ./publish

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: healthcheckfunc-jiga
          package: ./publish
